sentry:
  dsn: https://9fc07fdf536634533ad6956ca8f45d1e@o4505767793524736.ingest.sentry.io/4505767799095296
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0
server:
  port: 9001
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
group:
  cutoff-checker:
    time: 1800
    initial-check-delay: 0
    check-interval: 300
  loader:
    enabled: false
    initial-group-delay: 0
    initial-group-size: 3
    periodic-group-addition-interval: 300
    periodic-group-addition-count: 1

spring:
  application:
    name: group-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:5432/grouphq_group
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/grouphq_group
  cloud:
    function:
      definition: |
        handleGroupCreateRequests;
        handleGroupStatusRequests;
        handleGroupJoinRequests;
        handleGroupLeaveRequests;
        publishProcessedEvents
    stream:
      bindings:
        handleGroupCreateRequests-in-0:
          destination: group-create-requests
          group: ${spring.application.name}
        handleGroupStatusRequests-in-0:
          destination: group-status-requests
          group: ${spring.application.name}
        handleGroupJoinRequests-in-0:
          destination: group-join-requests
          group: ${spring.application.name}
        handleGroupLeaveRequests-in-0:
          destination: group-leave-requests
          group: ${spring.application.name}
        publishProcessedEvents-out-0:
          destination: group-event-results
  integration:
    poller:
      fixed-delay: 50
  rabbitmq:
    host: {$SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: user
    password: password
    connection-timeout: 5s
logging:
  level:
    root: info
    com.grouphq: debug
