server:
  error:
    include-stacktrace: never
spring:
  profiles:
    active: local
  r2dbc:
    url: r2dbc:postgresql://grouphq-postgres/grouphq_group
  flyway:
    url: jdbc:postgresql://grouphq-postgres/grouphq_group
  rabbitmq:
    host: grouphq-rabbitmq
group:
  cutoff-checker:
    time: 1800
    initial-check-delay: 0
    check-interval: 300
  loader:
    enabled: true
    initial-group-delay: 0
    initial-group-size: 3
    periodic-group-addition-interval: 300
    periodic-group-addition-count: 1
LOKI:
  URL: http://loki/loki/api/v1/push
ZIPKIN:
  HOST: tempo