server:
  error:
    include-stacktrace: never
spring:
  r2dbc:
    url: r2dbc:postgresql://grouphq-postgres/grouphq_group
  flyway:
    url: jdbc:postgresql://grouphq-postgres/grouphq_group
  rabbitmq:
    host: grouphq-rabbitmq
group:
  loader:
    enabled: true
    group-service-jobs:
      load-groups:
        initial-delay: 0
        fixed-delay: 2147483647
        initial-group-count: 3
        fixed-group-addition-count: 1
      expire-groups:
        initial-delay: 0
        fixed-delay: 300
        group-lifetime: 2147483647
      load-members:
        initial-delay: 2147483647
        fixed-delay: 60
        member-join-max-delay: 120