apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-service
  labels:
    app: group-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: group-service
  template:
    metadata:
      labels:
        app: group-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "9001"
    spec:
      containers:
        - name: group-service
          image: ghcr.io/grouphq/group-sync
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
          ports:
            - containerPort: 9001
          env:
            - name: BPL_DEBUG_ENABLED
              value: "true"
            - name: BPL_DEBUG_PORT
              value: "8001"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9001
            failureThreshold: 1
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9001
            failureThreshold: 50
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9001
            initialDelaySeconds: 30
            periodSeconds: 5
          volumeMounts:
            - name: group-service-config-volume
              mountPath: /workspace/config
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: group-service-config-volume
          configMap:
            name: group-service-config